version: '3.3'

services:
  DmcDispatcherWS :
    image: "sfr-dmc-tomcat:7"
    command: > 
      /bin/sh -c "cp /binDir/DmcDispatcherWS.tar.gz /configDir/DmcDispatcherWS.tar.gz && 
                  tar -xzf /configDir/DmcDispatcherWS.tar.gz && 
                  cp /binDir/DmcDispatcherWS.war /usr/local/tomcat/webapps/ && 
                  export JAVA_OPTS='-Dport.shutdown=8205 -Dport.http=8280 -DdmcWeb_configDir=/configDir -DdmcWeb_persoDir=/usr/local/tomcat/temp' && 
                  catalina.sh run ; exit 0"
    network_mode: host
    container_name: "DmcDispatcherWS"
    restart: "no"
    volumes:
      - $LOCAL_CONFIG_DIR:/configDir
      - $LOCAL_BIN_DIR/DmcDispatcherWS:/binDir
