version: '3.3'

services:
  eDMC :
    image: "tomcat:7"
    command: > 
      /bin/sh -c "export JAVA_OPTS='-DdmcWeb_configDir=/configDir -DdmcWeb_persoDir=/usr/local/tomcat/temp' && catalina.sh run ; exit 0"
    #  - catalina.sh run 
#    command: ["catalina.sh", "run", "JAVA_OPTS=\"-DdmcWeb_configDir=/devConfig -DdmcWeb_persoDir=/tmp\""]
    network_mode: host
    container_name: "eDMC"
    #hostname: eDMC
    restart: "no"
    cap_add:
      - SYS_PTRACE
    stdin_open: true
    tty: true
#    environment:
#    - JAVA_OPTS="-DdmcWeb_configDir=/devConfig -DdmcWeb_persoDir=/tmp"
#    - dmcWeb_configDir=/devConfig
#    - dmcWeb_persoDir=/tmp
#    cap_add:
#    - SYS_PTRACE
#    stdin_open: true
#    tty: true
#    ports:
#      - "8080:8080"
    volumes:
#      - type: bind
#        source: $LOCAL_CONFIG_DIR
#        target: /configDir1
#       - type: bind
#         source: /home/desktop/sfr/install/.m2/bin
#         target: /binDir
#      - type: bind
#        source: ./te
#        target: /test2
#        source: ./test1
#        target: /test1
      #- /home/desktop/sfr/projects/eDMC/target/eDMC-2.7.2-SNAPSHOT.war:/usr/local/tomcat/webapps/eDMC.war
      - $LOCAL_CONFIG_DIR/:/configDir/
      - /home/desktop/sfr/install/.m2/bin/:/binDir/
    privileged: true      