version: '3.3'

services:
  MugWS :
    image: "node:18-buster"
    command: > 
      /bin/sh -c "mkdir -p /usr/src/app && 
                  cd /usr/src/app && 
                  cp /binDir/MugWS.tar.gz . && 
                  tar -xzf MugWS.tar.gz && 
                  node server.js; exit 0"
    network_mode: host
    container_name: "MugWS"
    restart: "no"
    volumes:
      - $LOCAL_BIN_DIR/MugWS:/binDir

  openldap:
    image: bitnami/openldap:2
#    ports:
#      - '1389:1389'
#      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    network_mode: host
    volumes:
      - "./openldap/openldap_data:/bitnami/openldap"
