version: '3.3'

services:
  mongo:
    image: sfr-dmc-mongo
    restart: "no"
    container_name: mongo
    ports:
      - "27017:27017"
      - "24:24"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: "no"
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

volumes:
  mongo:
    name: "mongo"